### ISSUE TITLE
libsodium error

### ISSUE THREAD

**Issue by cakescripter** [mattantonelli/ffxiv-hunt-bot#1]
I installed libsodium as it told me to do, but it still doesnt work properly. 
![image](https://user-images.githubusercontent.com/54625887/63931922-7e82a480-ca56-11e9-965a-8b1ea2fd9829.png)

**Comment by mattantonelli** [comment]
The libsodium error is a warning from `discordrb` which you can safely ignore since the bot does not have any voice chat integration.

However, the real error you have is at the end: it cannot connect to Redis. I realize that I neglected to add this dependency to the README. You can read up on how to install Redis [here](https://redis.io/topics/quickstart).
